name: multi_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5'

dependencies:
  flutter:
    sdk: flutter

  go_router: 13.1.0

dev_dependencies:
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
